hidden_dim: 256
attention_heads: 4
linear_units: 1024
eblocks: 12
edropout: 0.1
cnn_module_kernel: 31

batch_bins: 6000000
accum_grad: 2
nepochs: 20
nworkers: 4
log_interval: 100

lr: 1e-4
wdecay: 1e-6
warmup_steps: 15000
