hidden_dim: 256
attention_heads: 4
linear_units: 1024
eblocks: 12
edropout: 0.1

batch_bins: 6000000
accum_grad: 2
nepochs: 20
nworkers: 2
log_interval: 100

lr: 1e-3
wdecay: 1e-6
warmup_steps: 15000
